---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: ~/Box Sync/Graduate School/Professional Development/CV-master/formatting.tex
geometry: margin=1in

title: "CV"
author: Elena R. Suglia
#orcid: "orcid.org/0000-0002-9577-6885"
jobtitle: "Center for Population Biology · University of California, Davis"
address: "2320 Storer Hall, Davis, CA 95616"
fontawesome: yes
email: esuglia@ucdavis.edu
#github: elena suglia?
#phone: "+1 555 5555"
web: 'elenasuglia.com'
updated: no

keywords: RMarkdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---
# Education

*University of California, Davis*, Ph.D. student, Population Biology, Adviser: Jennifer Gremer \hfill 2017-present

*Brown University*, B.A. Biology with honors, 3.88 GPA \hfill 2015

# Publications

Bertness, M.D., Brisson, C.P., Coverdale, T.C., Bevil, M.C., Crotty, S.M., and **E.R. Suglia.** 2014. Experimental predator removal causes rapid salt marsh die-off. *Ecology Letters* doi: 10.1111/ele.12287.

Yajima, M., **Suglia, E.R.**, Gustafson, E.A., and G.M. Wessel. 2013. Meiotic gene expression initiates during larval development in the sea urchin. *Developmental Dynamics* 242(2):155-63. doi: 10.1002/dvdy.23904.

# Research Experience

*PhD Student, Gremer Laboratory, University of California, Davis* \hfill 2017-present

> Studying plant responses to climate change using a combination of field, genomics, and modeling approaches. Specifically, investigating the effects of snowmelt timing on phenology and gene flow in several populations of the native California plant *Streptanthus tortuosus* at Lassen Volcanic National Park.

*Research Assistant, Schmitt Laboratory, University of California, Davis* \hfill 2016-2017

> Studied life history variation and local adaptation in the plant *Streptanthus tortuosus* across elevational and latitudinal clines in the context of its ability to adapt to climate change.


*Research Assistant, Winfree Laboratory, Rutgers University* \hfill 2015

> Conducted field work determining the effectiveness of pollinator habitat restoration strategies on native bees. Identified New Jersey bees and plants to species and curated insect and plant collections. Measured bee and floral traits to quantify trait matching.


*Research Assistant, Bertness Laboratory, Brown University* \hfill 2013-2015

> Performed field experiments in Cape Cod salt marshes demonstrating that recreational overfishing triggers a trophic cascade that leads to salt marsh die-off.

*Research Assistant, Wessel Laboratory, Brown University* \hfill 2013

> Studied expression of meiotic genes and proteins during echinoderm embryogenesis and gametogenesis. Designed and performed independent study researching possible splicing event in echinoderm meiotic gene dmc1.

# Academic Honors & Awards

Dean Marjorie Thompson Senior Prize in Biology, Brown University \hfill 2015

Sigma XI Scientific Research Honor Society \hfill 2015

USA Rugby All-Academic \hfill 2014

# Funding

Center for Population Biology Research Award, UC Davis (\$1200) \hfill 2018

Northern California Botanists Research Scholarship, CNPS Shasta Chapter (\$1000) \hfill 2018

Sharon Gray Memorial Award to fund mentorship activities, UC Davis (\$1000) \hfill 2017

NSF Graduate Research Fellowship Program Award (\$138,000) \hfill 2017

National Association of Science Writers Travel Fellowship to attend AAAS meeting (\$1500) \hfill 2015

Voss Environmental Fellowship, Brown University (\$3500) \hfill 2014

Undergraduate Teaching and Research Award, Brown University (\$3500) \hfill 2013
  
Summer Undergraduate Research Fellowship for Rhode Island NSF EPSCoR (\$4200) \hfill 2012

# Presentations

\vspace{-3mm}
*\* oral presentation, $\dagger$ poster presentation*

**E. Suglia.** The impact of snowmelt on phenology and population genetics of *Streptanthus tortuosus*. Population Biology Graduate Group Student Symposium, Davis, CA.* \hfill 2017

**E. Suglia,** M. Bertness, C. Brisson, T. Coverdale, M. Bevil, and S. Crotty. Experimental predator removal causes rapid salt marsh die-off. Benthics Ecology Meeting, Quebec City, Canada.* \hfill 2015

**E. Suglia**, M. Yajima, E. Gustafson, and G. Wessel. Expression of Meiotic Genes and Proteins During Echinoderm Embryogenesis and Gametogenesis. Rhode Island SURF Conference, Kingston, RI. $\dagger$ \hfill 2012

# Teaching Experience

*Teaching Assistant*, Introduction to Evolution, UC Davis \hfill Winter 2019

*Teaching Assistant*, Ecology and Evolution of Animal-Plant Interactions, UC Davis \hfill Fall 2018

*Teaching Assistant*, Principles of Ecology, Brown University \hfill Spring 2014, Spring 2015 

*Teaching Assistant*, Statistical Analysis of Biological Data, Brown University \hfill Spring 2015

*Teaching Assistant*, Environmental Scholarship and Communication, Brown University \hfill Spring 2015

*Teaching Assistant*, Coastal Ecology and Conservation, Brown University \hfill Fall 2015

*Democracy Coach*, Generation Citizen, Brown University \hfill Fall 2012

# Mentoring

*Mentees*: Vanessa Bassinello, Helena Bayat, Lahari Indraganti, Gautum Mathur, Joaquin Meckler-Pacheco, Ryan Moore, Lauren Okafor, Noah Rosenberg, John Schroder

**Mentored 9 undergraduates**, University of California, Davis \hfill 2016-present

> Summer research mentor for Evolution and Ecology Graduate Admissions Pathway program (LO), 2018

> Sharon Gray Memorial Award Mentor (LI), 2018. Accompanied mentee to California Native Plant Society 2018 Conservation Conference and Jepson Herbarium Introduction to Lichens Workshop

> Research Mentor for HB, JM, LI, LO. Assisted with project design, analytical approach, and poster presentation (HB, JM, LO); guided literature review, held weekly check-ins, oversaw research activities (HB, LI, LO)

> Aided in applications for jobs and fellowships, navigating degree and GPA, cover letter and resume writing (HB, JM); provided professional development advice and resources (HB, LI, JM, RM)

> Designed and ran a cover letter and resume writing workshop for two quarters

> Led scientific paper discussion group for three quarters

> Designed and taught introductory R programming workshops for two quarters


# Professional Service

## **Academic Organizations**

Equity in Science, Technology, Engineering, Math, and Entrepreneurship, University of California, Davis

> *Outreach Committee Member* (2017-present), https://esteme.weebly.com/

Women in Life Sciences at Davis, University of California, Davis

> *Administrator* (2018-present), https://wild.ucdavis.edu/

## **Professional Membership**

Ecological Society of America (Science Communication Section, Plant Population Ecology Section)

California Native Plant Society (Shasta Chapter, Mount Lassen Chapter)

Botanical Society of America (Ecological Section)

Davis Botanical Society (Center for Plant Diversity, University of California, Davis)

Society for the Study of Evolution

Friends of the Jepson Herbarium

Society for Herbarium Curators

National Association of Science Writers

# Professional Development

## **Research**

Introduction to R in GIS, University of California, Davis Data Science Initiative \hfill 2018

## **Teaching**

Fall Foundations in Teaching Workshop Series, UC Davis Center for Educational Effectiveness \hfill 2018

Teaching Philosophy Workshop, UC Davis Center for Educational Effectiveness \hfill 2018

Diversity Statement Workshop, UC Davis Center for Educational Effectiveness \hfill 2018

## **Diversity & Inclusion** 

Strengths Based Leadership Training for Diversity and Inclusion, UC Davis \hfill 2018

Diversity 102 Workshop, GradPathways, UC Davis Graduate Studies \hfill 2018

Foundations in LGBTQIA Allyship Training, UC Davis LGBTQIA Resource Center \hfill 2018

UndocuAlly Program for Educators, UC Davis AB540 and Undocumented Center \hfill 2017

Graduate Diversity Orientation Program Extension Workshops, UC Davis \hfill 2017-2018

# Outreach & Community Service

*Student Representative*, Population Biology Graduate Group Steering Committee, UC Davis \hfill 2018-2019

*Member*, Population Biology Graduate Group Diversity Committee, UC Davis \hfill 2018-present

*Steering Committee Member*, Graduates for Inclusion, Diversity, and Equity, UC Davis \hfill 2017-present

*Volunteer*, STEM Squad, Winters Middle School, Winters, CA \hfill 2017-present

>  https://estemestemsquad.weebly.com/ 

*Volunteer*, Roundtable Discussion, Holistic U Graduate Diversity Orientation, UC Davis \hfill 2018

*Volunteer*, Undergraduate Student Training in Academic Research, UC Davis \hfill 2018

*Volunteer*, Picnic Day Tree of Life Exhibit, UC Davis \hfill 2018

*Volunteer*, Family STEAM night, Barrett Middle School, Carmichael, CA \hfill 2017

# Science Communication | Writing Portfolio: \href{https://elenasuglia.journoportfolio.com/}{\tt $elenasuglia.journoportfolio.com$ } 

Contributing writer and editor, NPR's "Friends of Joe's Big Idea" SciComm group \hfill 2017-present

SciComm Workshop Series, Scholars Promoting Education Awareness and Knowledge, UC Davis \hfill 2017

Lead public Pollinator Walks in New Jersey discussing native bee diversity and conservation \hfill 2015

Organized and led 3-day Science Communication Colloquium, Brown University \hfill 2015

Published a This I Believe essay about salt marshes on Rhode Island National Public Radio \hfill 2015

## **Selected Science Writing**

Suglia, Elena. "What is the 'great nutrient collapse' and why haven't you heard about it?" Scientific American Blog. X December 2018. \href{https://www.XYZ/}{\tt $Link$ }

Suglia, Elena. “The Buzz on Bee Research at Fairview Farm.” Raritan Headwaters Association Newsletter. 29 October 2015. \href{https://www.raritanheadwaters.org/2015/10/29/the-buzz-on-bee-research-at-fairview-farm/}{\tt $Link$ }

Suglia, Elena. “Tardigrades: The tiny superheroes that have been to space.” Public Radio Exchange. 7 May 2015. \href{https://beta.prx.org/stories/148933}{\tt $Link$ }

Suglia, Elena. “Robots may soon swarm the ocean floor searching for resources.” National Association of Science Writers. 18 February 2015. \href{https://www.nasw.org/article/robots-may-soon-swarm-ocean-floor-searching-resources}{\tt $Link$ }

Suglia, Elena. “Accidental greatness: How some of the world’s most famous discoveries started with mistakes.” The College Hill Independent. 14 November 2014. \href{http://www.theindy.org/450}{\tt $Link$ }

Suglia, Elena. “Long time, no see: Insect antiquity and small body size contribute to insect diversity.” Brown University Catalyst Magazine, Fall 2014 edition.

Suglia, Elena and Sinead Crotty. “Salt Marsh Die-off: Causes and Consequences.” Association of Massachusetts Wetlands Scientists Newsletter. July 2014.

Suglia, Elena. “How do you teach a melting pot? Blend it up.” Brown University Behind the Science Newsletter. April 15, 2014. \href{http://blogs.brown.edu/behind-the-science/2014/04/21/how-do-you-teach-a-melting-pot-blend-it-up/}{\tt $Link$ }

# Skills

\begin{tabbing}
\textit{Programming:} \= R (\textit{intermediate})\\ [1.5ex]
\textit{Software:} \> JMP, MySQL, G*Power, SAS, Audacity, ImageJ, GIS, Microsoft Office \\ [1.5ex]
\end{tabbing}

